// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'manager.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'settings.dart';

Future<void> initCore() => RustLib.instance.api.crateApiInitCore();

/// Subscribe to status changes. The current status is pushed immediately.
Stream<Status> watchEvents() => RustLib.instance.api.crateApiWatchEvents();

Future<Status> getStatus() => RustLib.instance.api.crateApiGetStatus();

Future<Settings> getSettings() => RustLib.instance.api.crateApiGetSettings();

Future<void> saveSettings({required Settings s}) =>
    RustLib.instance.api.crateApiSaveSettings(s: s);

Future<void> setAwake({required bool on_}) =>
    RustLib.instance.api.crateApiSetAwake(on_: on_);

Future<void> setAutoBlackout({required bool on_}) =>
    RustLib.instance.api.crateApiSetAutoBlackout(on_: on_);

Future<void> blackoutNow() => RustLib.instance.api.crateApiBlackoutNow();

Future<void> clearBlackout() => RustLib.instance.api.crateApiClearBlackout();

/// Restore the power state before process exit (Dart calls `exit()` after).
Future<void> prepareQuit() => RustLib.instance.api.crateApiPrepareQuit();

/// Process singleton. Returns true for the first owner; later instances
/// should focus the existing settings window and exit.
Future<bool> ensureSingleInstance() =>
    RustLib.instance.api.crateApiEnsureSingleInstance();

/// Bring the first instance's settings window forward. Best-effort.
Future<bool> focusExistingWindow() =>
    RustLib.instance.api.crateApiFocusExistingWindow();
