// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'manager.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import 'settings.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1478416173;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'caffeine_core',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<bool> crateApiAutostartEnabled();

  Future<void> crateApiBlackoutNow();

  Future<void> crateApiClearBlackout();

  Future<bool> crateApiEnsureSingleInstance();

  Future<bool> crateApiFocusExistingWindow();

  Future<Settings> crateApiGetSettings();

  Future<Status> crateApiGetStatus();

  Future<void> crateApiInitCore();

  Future<void> crateApiPrepareQuit();

  Future<void> crateApiSaveSettings({required Settings s});

  Future<void> crateApiSetAutoBlackout({required bool on_});

  Future<void> crateApiSetAutostart({required bool on_});

  Future<void> crateApiSetAwake({required bool on_});

  Future<void> crateApiSetCursorFindEnabled({required bool on_});

  Future<void> crateApiSetOsdEnabled({required bool on_});

  Stream<Status> crateApiWatchEvents();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<bool> crateApiAutostartEnabled() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiAutostartEnabledConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiAutostartEnabledConstMeta =>
      const TaskConstMeta(debugName: "autostart_enabled", argNames: []);

  @override
  Future<void> crateApiBlackoutNow() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiBlackoutNowConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiBlackoutNowConstMeta =>
      const TaskConstMeta(debugName: "blackout_now", argNames: []);

  @override
  Future<void> crateApiClearBlackout() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiClearBlackoutConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiClearBlackoutConstMeta =>
      const TaskConstMeta(debugName: "clear_blackout", argNames: []);

  @override
  Future<bool> crateApiEnsureSingleInstance() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiEnsureSingleInstanceConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiEnsureSingleInstanceConstMeta =>
      const TaskConstMeta(debugName: "ensure_single_instance", argNames: []);

  @override
  Future<bool> crateApiFocusExistingWindow() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiFocusExistingWindowConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiFocusExistingWindowConstMeta =>
      const TaskConstMeta(debugName: "focus_existing_window", argNames: []);

  @override
  Future<Settings> crateApiGetSettings() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_settings,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetSettingsConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetSettingsConstMeta =>
      const TaskConstMeta(debugName: "get_settings", argNames: []);

  @override
  Future<Status> crateApiGetStatus() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_status,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiGetStatusConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiGetStatusConstMeta =>
      const TaskConstMeta(debugName: "get_status", argNames: []);

  @override
  Future<void> crateApiInitCore() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiInitCoreConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiInitCoreConstMeta =>
      const TaskConstMeta(debugName: "init_core", argNames: []);

  @override
  Future<void> crateApiPrepareQuit() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPrepareQuitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPrepareQuitConstMeta =>
      const TaskConstMeta(debugName: "prepare_quit", argNames: []);

  @override
  Future<void> crateApiSaveSettings({required Settings s}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_box_autoadd_settings(s, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSaveSettingsConstMeta,
        argValues: [s],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSaveSettingsConstMeta =>
      const TaskConstMeta(debugName: "save_settings", argNames: ["s"]);

  @override
  Future<void> crateApiSetAutoBlackout({required bool on_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(on_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetAutoBlackoutConstMeta,
        argValues: [on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetAutoBlackoutConstMeta =>
      const TaskConstMeta(debugName: "set_auto_blackout", argNames: ["on_"]);

  @override
  Future<void> crateApiSetAutostart({required bool on_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(on_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSetAutostartConstMeta,
        argValues: [on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetAutostartConstMeta =>
      const TaskConstMeta(debugName: "set_autostart", argNames: ["on_"]);

  @override
  Future<void> crateApiSetAwake({required bool on_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(on_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetAwakeConstMeta,
        argValues: [on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetAwakeConstMeta =>
      const TaskConstMeta(debugName: "set_awake", argNames: ["on_"]);

  @override
  Future<void> crateApiSetCursorFindEnabled({required bool on_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(on_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetCursorFindEnabledConstMeta,
        argValues: [on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetCursorFindEnabledConstMeta =>
      const TaskConstMeta(
        debugName: "set_cursor_find_enabled",
        argNames: ["on_"],
      );

  @override
  Future<void> crateApiSetOsdEnabled({required bool on_}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_bool(on_, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSetOsdEnabledConstMeta,
        argValues: [on_],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSetOsdEnabledConstMeta =>
      const TaskConstMeta(debugName: "set_osd_enabled", argNames: ["on_"]);

  @override
  Stream<Status> crateApiWatchEvents() {
    final sink = RustStreamSink<Status>();
    unawaited(
      handler.executeNormal(
        NormalTask(
          callFfi: (port_) {
            final serializer = SseSerializer(generalizedFrbRustBinding);
            sse_encode_StreamSink_status_Sse(sink, serializer);
            pdeCallFfi(
              generalizedFrbRustBinding,
              serializer,
              funcId: 16,
              port: port_,
            );
          },
          codec: SseCodec(
            decodeSuccessData: sse_decode_unit,
            decodeErrorData: null,
          ),
          constMeta: kCrateApiWatchEventsConstMeta,
          argValues: [sink],
          apiImpl: this,
        ),
      ),
    );
    return sink.stream;
  }

  TaskConstMeta get kCrateApiWatchEventsConstMeta =>
      const TaskConstMeta(debugName: "watch_events", argNames: ["sink"]);

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<Status> dco_decode_StreamSink_status_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Settings dco_decode_box_autoadd_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_settings(raw);
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  OsdPosition dco_decode_osd_position(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return OsdPosition.values[raw as int];
  }

  @protected
  Settings dco_decode_settings(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12)
      throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return Settings(
      awakeEnabled: dco_decode_bool(arr[0]),
      autoBlackoutEnabled: dco_decode_bool(arr[1]),
      autoBlackoutSecs: dco_decode_u_64(arr[2]),
      unlockKey: dco_decode_unlock_key(arr[3]),
      unlockMouse: dco_decode_unlock_mouse(arr[4]),
      startMinimized: dco_decode_bool(arr[5]),
      osdEnabled: dco_decode_bool(arr[6]),
      osdPosition: dco_decode_osd_position(arr[7]),
      cursorFindEnabled: dco_decode_bool(arr[8]),
      cursorFindMagnify: dco_decode_bool(arr[9]),
      cursorFindRipple: dco_decode_bool(arr[10]),
      cursorFindArrows: dco_decode_bool(arr[11]),
    );
  }

  @protected
  Status dco_decode_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return Status(
      awake: dco_decode_bool(arr[0]),
      blackout: dco_decode_bool(arr[1]),
      autoBlackout: dco_decode_bool(arr[2]),
      autoBlackoutSecs: dco_decode_u_64(arr[3]),
      osdEnabled: dco_decode_bool(arr[4]),
      cursorFindEnabled: dco_decode_bool(arr[5]),
      version: dco_decode_String(arr[6]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  UnlockKey dco_decode_unlock_key(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UnlockKey.values[raw as int];
  }

  @protected
  UnlockMouse dco_decode_unlock_mouse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return UnlockMouse.values[raw as int];
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<Status> sse_decode_StreamSink_status_Sse(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Settings sse_decode_box_autoadd_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_settings(deserializer));
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  OsdPosition sse_decode_osd_position(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return OsdPosition.values[inner];
  }

  @protected
  Settings sse_decode_settings(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_awakeEnabled = sse_decode_bool(deserializer);
    var var_autoBlackoutEnabled = sse_decode_bool(deserializer);
    var var_autoBlackoutSecs = sse_decode_u_64(deserializer);
    var var_unlockKey = sse_decode_unlock_key(deserializer);
    var var_unlockMouse = sse_decode_unlock_mouse(deserializer);
    var var_startMinimized = sse_decode_bool(deserializer);
    var var_osdEnabled = sse_decode_bool(deserializer);
    var var_osdPosition = sse_decode_osd_position(deserializer);
    var var_cursorFindEnabled = sse_decode_bool(deserializer);
    var var_cursorFindMagnify = sse_decode_bool(deserializer);
    var var_cursorFindRipple = sse_decode_bool(deserializer);
    var var_cursorFindArrows = sse_decode_bool(deserializer);
    return Settings(
      awakeEnabled: var_awakeEnabled,
      autoBlackoutEnabled: var_autoBlackoutEnabled,
      autoBlackoutSecs: var_autoBlackoutSecs,
      unlockKey: var_unlockKey,
      unlockMouse: var_unlockMouse,
      startMinimized: var_startMinimized,
      osdEnabled: var_osdEnabled,
      osdPosition: var_osdPosition,
      cursorFindEnabled: var_cursorFindEnabled,
      cursorFindMagnify: var_cursorFindMagnify,
      cursorFindRipple: var_cursorFindRipple,
      cursorFindArrows: var_cursorFindArrows,
    );
  }

  @protected
  Status sse_decode_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_awake = sse_decode_bool(deserializer);
    var var_blackout = sse_decode_bool(deserializer);
    var var_autoBlackout = sse_decode_bool(deserializer);
    var var_autoBlackoutSecs = sse_decode_u_64(deserializer);
    var var_osdEnabled = sse_decode_bool(deserializer);
    var var_cursorFindEnabled = sse_decode_bool(deserializer);
    var var_version = sse_decode_String(deserializer);
    return Status(
      awake: var_awake,
      blackout: var_blackout,
      autoBlackout: var_autoBlackout,
      autoBlackoutSecs: var_autoBlackoutSecs,
      osdEnabled: var_osdEnabled,
      cursorFindEnabled: var_cursorFindEnabled,
      version: var_version,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  UnlockKey sse_decode_unlock_key(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return UnlockKey.values[inner];
  }

  @protected
  UnlockMouse sse_decode_unlock_mouse(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return UnlockMouse.values[inner];
  }

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_status_Sse(
    RustStreamSink<Status> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
      self.setupAndSerialize(
        codec: SseCodec(
          decodeSuccessData: sse_decode_status,
          decodeErrorData: sse_decode_AnyhowException,
        ),
      ),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_settings(
    Settings self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_settings(self, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_osd_position(OsdPosition self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_settings(Settings self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.awakeEnabled, serializer);
    sse_encode_bool(self.autoBlackoutEnabled, serializer);
    sse_encode_u_64(self.autoBlackoutSecs, serializer);
    sse_encode_unlock_key(self.unlockKey, serializer);
    sse_encode_unlock_mouse(self.unlockMouse, serializer);
    sse_encode_bool(self.startMinimized, serializer);
    sse_encode_bool(self.osdEnabled, serializer);
    sse_encode_osd_position(self.osdPosition, serializer);
    sse_encode_bool(self.cursorFindEnabled, serializer);
    sse_encode_bool(self.cursorFindMagnify, serializer);
    sse_encode_bool(self.cursorFindRipple, serializer);
    sse_encode_bool(self.cursorFindArrows, serializer);
  }

  @protected
  void sse_encode_status(Status self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.awake, serializer);
    sse_encode_bool(self.blackout, serializer);
    sse_encode_bool(self.autoBlackout, serializer);
    sse_encode_u_64(self.autoBlackoutSecs, serializer);
    sse_encode_bool(self.osdEnabled, serializer);
    sse_encode_bool(self.cursorFindEnabled, serializer);
    sse_encode_String(self.version, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_unlock_key(UnlockKey self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_unlock_mouse(UnlockMouse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }
}
