// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Status {
  final bool awake;
  final bool blackout;
  final bool autoBlackout;
  final BigInt autoBlackoutSecs;

  /// Status OSD toggle (also surfaced in the tray menu).
  final bool osdEnabled;

  /// Shake-to-find-the-cursor toggle (also surfaced in the tray menu).
  final bool cursorFindEnabled;
  final String version;

  const Status({
    required this.awake,
    required this.blackout,
    required this.autoBlackout,
    required this.autoBlackoutSecs,
    required this.osdEnabled,
    required this.cursorFindEnabled,
    required this.version,
  });

  @override
  int get hashCode =>
      awake.hashCode ^
      blackout.hashCode ^
      autoBlackout.hashCode ^
      autoBlackoutSecs.hashCode ^
      osdEnabled.hashCode ^
      cursorFindEnabled.hashCode ^
      version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Status &&
          runtimeType == other.runtimeType &&
          awake == other.awake &&
          blackout == other.blackout &&
          autoBlackout == other.autoBlackout &&
          autoBlackoutSecs == other.autoBlackoutSecs &&
          osdEnabled == other.osdEnabled &&
          cursorFindEnabled == other.cursorFindEnabled &&
          version == other.version;
}
