// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class Settings {
  /// Keep display/system awake via SetThreadExecutionState.
  final bool awakeEnabled;

  /// Auto blackout after N idle seconds (toggle).
  final bool autoBlackoutEnabled;

  /// Idle seconds before auto blackout.
  final BigInt autoBlackoutSecs;

  /// Keyboard dismiss method.
  final UnlockKey unlockKey;

  /// Mouse dismiss method.
  final UnlockMouse unlockMouse;

  /// Start minimized to tray (settings window hidden).
  final bool startMinimized;

  const Settings({
    required this.awakeEnabled,
    required this.autoBlackoutEnabled,
    required this.autoBlackoutSecs,
    required this.unlockKey,
    required this.unlockMouse,
    required this.startMinimized,
  });

  @override
  int get hashCode =>
      awakeEnabled.hashCode ^
      autoBlackoutEnabled.hashCode ^
      autoBlackoutSecs.hashCode ^
      unlockKey.hashCode ^
      unlockMouse.hashCode ^
      startMinimized.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          awakeEnabled == other.awakeEnabled &&
          autoBlackoutEnabled == other.autoBlackoutEnabled &&
          autoBlackoutSecs == other.autoBlackoutSecs &&
          unlockKey == other.unlockKey &&
          unlockMouse == other.unlockMouse &&
          startMinimized == other.startMinimized;
}

/// How the blackout overlay is dismissed via keyboard.
enum UnlockKey {
  /// Any key press dismisses.
  any,

  /// Only ESC dismisses.
  esc,

  /// Only Space dismisses.
  space,

  /// Only Enter dismisses.
  enter,
}

/// How the blackout overlay is dismissed via mouse.
enum UnlockMouse {
  /// Mouse never dismisses (keyboard only). Recommended while an AI
  /// Computer-Use agent is driving the pointer.
  off,

  /// Any pointer movement beyond a small threshold dismisses.
  move,

  /// A deliberate side-to-side "shake" dismisses. AI-friendly: straight
  /// synthetic mouse paths almost never match a shake pattern.
  shake,

  /// Any mouse button click dismisses.
  click,
}
