// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Where the status OSD is anchored on the primary monitor.
enum OsdPosition {
  topLeft,
  topCenter,
  topRight,
  middleLeft,
  center,
  middleRight,
  bottomLeft,
  bottomCenter,
  bottomRight,
}

class Settings {
  /// Keep display/system awake via SetThreadExecutionState.
  final bool awakeEnabled;

  /// Auto blackout after N idle seconds (toggle).
  final bool autoBlackoutEnabled;

  /// Idle seconds before auto blackout.
  final BigInt autoBlackoutSecs;

  /// Keyboard dismiss method.
  final UnlockKey unlockKey;

  /// Mouse dismiss method.
  final UnlockMouse unlockMouse;

  /// Start minimized to tray (settings window hidden).
  final bool startMinimized;

  /// Show the tiny always-on-top status OSD (capture-excluded).
  final bool osdEnabled;

  /// OSD anchor position (9-way).
  final OsdPosition osdPosition;

  /// Shake the pointer side-to-side to spotlight the cursor.
  final bool cursorFindEnabled;

  /// While spotlighting, monitors without the cursor show an arrow
  /// pointing toward the monitor that has it.
  final bool cursorFindArrows;

  const Settings({
    required this.awakeEnabled,
    required this.autoBlackoutEnabled,
    required this.autoBlackoutSecs,
    required this.unlockKey,
    required this.unlockMouse,
    required this.startMinimized,
    required this.osdEnabled,
    required this.osdPosition,
    required this.cursorFindEnabled,
    required this.cursorFindArrows,
  });

  @override
  int get hashCode =>
      awakeEnabled.hashCode ^
      autoBlackoutEnabled.hashCode ^
      autoBlackoutSecs.hashCode ^
      unlockKey.hashCode ^
      unlockMouse.hashCode ^
      startMinimized.hashCode ^
      osdEnabled.hashCode ^
      osdPosition.hashCode ^
      cursorFindEnabled.hashCode ^
      cursorFindArrows.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Settings &&
          runtimeType == other.runtimeType &&
          awakeEnabled == other.awakeEnabled &&
          autoBlackoutEnabled == other.autoBlackoutEnabled &&
          autoBlackoutSecs == other.autoBlackoutSecs &&
          unlockKey == other.unlockKey &&
          unlockMouse == other.unlockMouse &&
          startMinimized == other.startMinimized &&
          osdEnabled == other.osdEnabled &&
          osdPosition == other.osdPosition &&
          cursorFindEnabled == other.cursorFindEnabled &&
          cursorFindArrows == other.cursorFindArrows;
}

/// How the blackout overlay is dismissed via keyboard.
enum UnlockKey {
  /// Any key press dismisses.
  any,

  /// Only ESC dismisses.
  esc,

  /// Only Space dismisses.
  space,

  /// Only Enter dismisses.
  enter,
}

/// How the blackout overlay is dismissed via mouse.
enum UnlockMouse {
  /// Mouse never dismisses (keyboard only). Recommended while an AI
  /// Computer-Use agent is driving the pointer.
  off,

  /// Any pointer movement beyond a small threshold dismisses.
  move,

  /// A deliberate side-to-side "shake" dismisses. AI-friendly: straight
  /// synthetic mouse paths almost never match a shake pattern.
  shake,

  /// Any mouse button click dismisses.
  click,
}
